### ISSUE TITLE
Resource revisions in bundles are ignored

### ISSUE THREAD

**Issue by Cynerva** [juju-solutions/cdk-shrinkwrap#10]
Given a bundle that includes something like this:

```
services:
  flannel:
    charm: cs:~containers/flannel-339
    resources:
      flannel-amd64: 3
      flannel-arm64: 1
      flannel-s390x: 3
```

Shrinkwrap will ignore those resource revisions and use whatever the charm store gives it instead.

Related, but not a fix: https://github.com/juju-solutions/cdk-shrinkwrap/pull/9
